### ISSUE TITLE
boolean and, or operation optimization

### ISSUE THREAD

**Issue by eujungkim** [Redempt/Crunch#12]
For following cases, second.getValue() is not required.
- operator : BOOLEAN_AND, first.getValue : false
- operator : BOOLEAN_OR, first.getValue : true

I think it can help to increase performance especially in case of using LazyVariable with complex logic  like below.

> env.addLazyVariable("complexFunction", () -> {
            // complex logic which need long calculation time
        }); 

So how about changing `getValue` method in `redempt.crunch.token.Operation`?

Before
>
	@Override
	public double getValue() {
		return operator.isUnary() ? operator.operate(first.getValue()) : operator.operate(first.getValue(), second.getValue());
	}

After
> 
	@Override
	public double getValue() {
	    if (operator.isUnary()) {
	        return operator.operate(first.getValue());
	    } else {
	        if (operator.name().equals(Operator.BOOLEAN_AND.name())) {
	            if (first.getValue() == Constant.FALSE.getValue()) {
	                return Constant.FALSE.getValue();
	            }
	        } else if (operator.name().equals(Operator.BOOLEAN_OR.name())) {
	            if (first.getValue() == Constant.TRUE.getValue()) {
                    return Constant.TRUE.getValue();
                }
	        }
	        return operator.operate(first.getValue(), second.getValue());
	    }
	}

**Comment by Redempt** [comment]
While I would like to implement short circuiting, I don't think this is a good design for it. I would like each individual operator to be able to specify that kind of behavior declaratively, and that's not really feasible with the current design unfortunately.

**Comment by eujungkim** [comment]
Thank you for your feedback.
