### ISSUE TITLE
find bug in solver, line 96

### ISSUE THREAD

**Issue by june1819** [Redempt/Crunch#7]
code : step *= random.nextDouble(Math.sqrt(minError));
I use maven to build source for jar.  But code didn't know locate in Random.nextDouble or ThreadLocalRandom.nextDouble! 

Please help me check out,  maven project https: https://github.com/june1819/Crunch-master.git

thank you

**Comment by Redempt** [comment]
I'm really not clear on what's being reported with this issue. Could you clarify? Are you getting any errors or unexpected behavior? What are you trying to do?
