### ISSUE TITLE
Precision issue on simple multiply

### ISSUE THREAD

**Issue by steviemo** [Redempt/Crunch#8]
Hey! Awesome library BTW. Just noticing some strange behaviour with some simple multiplication:
`Crunch.evaluateExpression("3.2 * 4.7") is resolving to 15.040000000000001`
Does this seem right to you? I would have expected just `15.04`.
Thanks!

**Comment by Redempt** [comment]
This is a floating point error. It happens no matter what.
![image](https://user-images.githubusercontent.com/14198267/208484864-9b77b611-6030-4814-a832-88596d91211d.png)

**Comment by steviemo** [comment]
Thanks!
